parameters:
#    portfolio_portfolio.example.class: Portfolio\PortfolioBundle\Example

services:
#    portfolio_portfolio.example:
#        class: %portfolio_portfolio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
